-- MySQL Script generated by MySQL Workbench
-- Wed Apr 17 19:57:46 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema helperRoads
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema helperRoads
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `helperRoads` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `helperRoads` ;

-- -----------------------------------------------------
-- Table `helperRoads`.`Cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helperRoads`.`Cities` (
  `CityID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`CityID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `helperRoads`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helperRoads`.`Users` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL DEFAULT NULL,
  `PhoneNumber` VARCHAR(20) NULL DEFAULT NULL,
  `Email` VARCHAR(255) NULL DEFAULT NULL,
  `Password` VARCHAR(255) NULL DEFAULT NULL,
  `RegistrationDate` DATE NULL DEFAULT NULL,
  `ProfileImage` VARCHAR(255) NULL DEFAULT NULL,
  `CityID` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`UserID`),
  INDEX `CityID` (`CityID` ASC) VISIBLE,
  CONSTRAINT `Users_ibfk_1`
    FOREIGN KEY (`CityID`)
    REFERENCES `helperRoads`.`Cities` (`CityID`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `helperRoads`.`AdvertisementsPlans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helperRoads`.`AdvertisementsPlans` (
  `PlanID` INT NOT NULL AUTO_INCREMENT,
  `PlanName` VARCHAR(50) NULL DEFAULT NULL,
  `DurationInDays` INT NULL DEFAULT NULL,
  `Cost` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`PlanID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `helperRoads`.`Payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helperRoads`.`Payments` (
  `PaymentsID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NULL DEFAULT NULL,
  `Amount` DECIMAL(10,2) NULL DEFAULT NULL,
  `PaymentDate` DATE NULL DEFAULT NULL,
  `IsActive` TINYINT(1) NULL DEFAULT NULL,
  `PlanID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`PaymentsID`),
  INDEX `UserID` (`UserID` ASC) VISIBLE,
  INDEX `PlanID` (`PlanID` ASC) VISIBLE,
  CONSTRAINT `Payments_ibfk_1`
    FOREIGN KEY (`UserID`)
    REFERENCES `helperRoads`.`Users` (`UserID`),
  CONSTRAINT `Payments_ibfk_2`
    FOREIGN KEY (`PlanID`)
    REFERENCES `helperRoads`.`AdvertisementsPlans` (`PlanID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `helperRoads`.`Advertisements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helperRoads`.`Advertisements` (
  `AdvertisementsID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NULL DEFAULT NULL,
  `Content` TEXT NULL DEFAULT NULL,
  `ImageLink` VARCHAR(255) NULL DEFAULT NULL,
  `IsActive` TINYINT(1) NULL DEFAULT NULL,
  `PlanID` INT NULL DEFAULT NULL,
  `PaymentsID` INT NULL DEFAULT NULL,
  `Link` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`AdvertisementsID`),
  INDEX `UserID` (`UserID` ASC) VISIBLE,
  INDEX `PlanID` (`PlanID` ASC) VISIBLE,
  INDEX `PaymentsID` (`PaymentsID` ASC) VISIBLE,
  CONSTRAINT `Advertisements_ibfk_1`
    FOREIGN KEY (`UserID`)
    REFERENCES `helperRoads`.`Users` (`UserID`),
  CONSTRAINT `Advertisements_ibfk_2`
    FOREIGN KEY (`PlanID`)
    REFERENCES `helperRoads`.`AdvertisementsPlans` (`PlanID`),
  CONSTRAINT `Advertisements_ibfk_3`
    FOREIGN KEY (`PaymentsID`)
    REFERENCES `helperRoads`.`Payments` (`PaymentsID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `helperRoads`.`ServiceTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helperRoads`.`ServiceTypes` (
  `ServiceID` INT NOT NULL,
  `Name` VARCHAR(255) NULL DEFAULT NULL,
  `Icon` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ServiceID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `helperRoads`.`Companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helperRoads`.`Companies` (
  `CompanyID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL DEFAULT NULL,
  `ServiceID` INT NULL DEFAULT NULL,
  `PhoneNumber` VARCHAR(20) NULL DEFAULT NULL,
  `Email` VARCHAR(255) NULL DEFAULT NULL,
  `Website` VARCHAR(255) NULL DEFAULT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  `LogoImage` VARCHAR(255) NULL DEFAULT NULL,
  `CityID` INT NULL DEFAULT NULL,
  `UserID` INT NULL DEFAULT NULL,
  `Neighborhood` VARCHAR(255) NULL DEFAULT NULL,
  `Street` VARCHAR(255) NULL DEFAULT NULL,
  `NumberLocation` VARCHAR(50) NULL DEFAULT NULL,
  `CEP` VARCHAR(10) NULL DEFAULT NULL,
  `Latitude` DECIMAL(9,6) NULL DEFAULT NULL,
  `Longitude` DECIMAL(9,6) NULL DEFAULT NULL,
  PRIMARY KEY (`CompanyID`),
  INDEX `ServiceID` (`ServiceID` ASC) VISIBLE,
  INDEX `CityID` (`CityID` ASC) VISIBLE,
  INDEX `FK_UserID` (`UserID` ASC) VISIBLE,
  CONSTRAINT `Companies_ibfk_1`
    FOREIGN KEY (`ServiceID`)
    REFERENCES `helperRoads`.`ServiceTypes` (`ServiceID`),
  CONSTRAINT `Companies_ibfk_2`
    FOREIGN KEY (`CityID`)
    REFERENCES `helperRoads`.`Cities` (`CityID`),
  CONSTRAINT `FK_UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `helperRoads`.`Users` (`UserID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `helperRoads`.`CompanyGallery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helperRoads`.`CompanyGallery` (
  `CompanyGalleryID` INT NOT NULL AUTO_INCREMENT,
  `CompanyID` INT NULL DEFAULT NULL,
  `ImagePath` VARCHAR(255) NULL DEFAULT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`CompanyGalleryID`),
  INDEX `CompanyID` (`CompanyID` ASC) VISIBLE,
  CONSTRAINT `CompanyGallery_ibfk_1`
    FOREIGN KEY (`CompanyID`)
    REFERENCES `helperRoads`.`Companies` (`CompanyID`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `helperRoads`.`CompanyReviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helperRoads`.`CompanyReviews` (
  `ReviewID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NULL DEFAULT NULL,
  `CompanyID` INT NULL DEFAULT NULL,
  `Rating` INT NULL DEFAULT NULL,
  `Comment` TEXT NULL DEFAULT NULL,
  `ReviewDate` DATE NULL DEFAULT NULL,
  `Type` ENUM('Rating', 'Comment') NOT NULL,
  PRIMARY KEY (`ReviewID`),
  INDEX `UserID` (`UserID` ASC) VISIBLE,
  INDEX `CompanyID` (`CompanyID` ASC) VISIBLE,
  CONSTRAINT `CompanyReviews_ibfk_1`
    FOREIGN KEY (`UserID`)
    REFERENCES `helperRoads`.`Users` (`UserID`),
  CONSTRAINT `CompanyReviews_ibfk_2`
    FOREIGN KEY (`CompanyID`)
    REFERENCES `helperRoads`.`Companies` (`CompanyID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `helperRoads`.`ServiceHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helperRoads`.`ServiceHistory` (
  `ServiceHistoryID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NULL DEFAULT NULL,
  `CompanyID` INT NULL DEFAULT NULL,
  `ServiceType` VARCHAR(255) NULL DEFAULT NULL,
  `ServiceDate` DATE NULL DEFAULT NULL,
  `Comments` TEXT NULL DEFAULT NULL,
  `Rating` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ServiceHistoryID`),
  INDEX `UserID` (`UserID` ASC) VISIBLE,
  INDEX `CompanyID` (`CompanyID` ASC) VISIBLE,
  CONSTRAINT `ServiceHistory_ibfk_1`
    FOREIGN KEY (`UserID`)
    REFERENCES `helperRoads`.`Users` (`UserID`),
  CONSTRAINT `ServiceHistory_ibfk_2`
    FOREIGN KEY (`CompanyID`)
    REFERENCES `helperRoads`.`Companies` (`CompanyID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `helperRoads`.`SocialMediaProfiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helperRoads`.`SocialMediaProfiles` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CompanyID` INT NULL DEFAULT NULL,
  `Platform` VARCHAR(50) NULL DEFAULT NULL,
  `ProfileLink` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `CompanyID` (`CompanyID` ASC) VISIBLE,
  CONSTRAINT `SocialMediaProfiles_ibfk_1`
    FOREIGN KEY (`CompanyID`)
    REFERENCES `helperRoads`.`Companies` (`CompanyID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
